In [2]:
import numpy as np
import torch
import os
import random
import tensorflow as tf

#câu1

In [4]:
#khởi tạo hai mảng ngẫu nhiên bằng numpy
seed = 2024
np.random.seed(seed)
array_np_1 = np.random.randint(-10,10,size=(3,4))
array_np_2 = np.random.randint(-10,10,size=(3,4))
array_np_2_trp = np.transpose(array_np_2)
array_multi = array_np_1.dot(array_np_2_trp)
print(f"Matran số 1: {array_np_1}")
print(f"Matran số 2: {array_np_2}")
print(f"Matran nghịch đảo của matran số 2: {array_np_2_trp}")
print(f"Phép nhân hai ma trận: {array_multi}")


Matran số 1: [[ -2 -10 -10  -6]
 [ -1  -9  -7   0]
 [ -8 -10  -5   7]]
Matran số 2: [[ 5  0  4  5]
 [ 1 -3  8 -1]
 [-4  0 -9 -5]]
Matran nghịch đảo của matran số 2: [[ 5  1 -4]
 [ 0 -3  0]
 [ 4  8 -9]
 [ 5 -1 -5]]
Phép nhân hai ma trận: [[-80 -46 128]
 [-33 -30  67]
 [-25 -25  42]]


In [12]:
#khởi tạo hai mảng ngẫu nhiên bằng torch
seed = 2024
torch.manual_seed(seed)
torch_arrray_1 = torch.randint(-10,10,size=(3,4))
torch_arrray_2 = torch.randint(-10,10,size=(3,4))
torch_arrray_2_trp = torch.t(torch_arrray_2)
torch_multi = torch.mm(torch_arrray_1,torch_arrray_2_trp)
print(f"Matran số 1: {torch_arrray_1}")
print(f"Matran số 2: {torch_arrray_2}")
print(f"Matran nghịch đảo của matran số 2: {torch_arrray_2_trp}")
print(f"Phép nhân hai ma trận: {torch_multi}")

Matran số 1: tensor([[  2,   0,  -6, -10],
        [ -7, -10,   0,   1],
        [  3,   9,   7,  -6]])
Matran số 2: tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]])
Matran nghịch đảo của matran số 2: tensor([[  1,  -9,  -3],
        [  8, -10,  -7],
        [  0,  -9,  -4],
        [ -2,   0,   8]])
Phép nhân hai ma trận: tensor([[  22,   36,  -62],
        [ -89,  163,   99],
        [  87, -180, -148]])


In [22]:
#khởi tạo hai mảng ngẫu nhiên bằng tensorflow
seed = 2024
tf.random.set_seed(seed)

tf_array_1 = tf.random.uniform((3,4),-10,10,tf.int32)
tf_array_2 = tf.random.uniform((3,4),-10,10,tf.int32)
tf_array_2_trp = tf.transpose(tf_array_2)
tf_multi = tf.matmul(tf_array_1,tf_array_2_trp)

print(f"Matran số 1: {tf_array_1}")
print(f"Matran số 2: {tf_array_2}")
print(f"Matran nghịch đảo của matran số 2: {tf_array_2_trp}")
print(f"Phép nhân hai ma trận: {tf_multi}")

Matran số 1: [[-6 -2  0 -2]
 [ 4  4 -9  3]
 [ 7  1  2 -5]]
Matran số 2: [[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]]
Matran nghịch đảo của matran số 2: [[-3  2  4]
 [-7 -5 -3]
 [ 9 -3 -3]
 [ 3 -5  5]]
Phép nhân hai ma trận: [[  26    8  -28]
 [-112    0   46]
 [ -25   28   -6]]


Câu 2

In [26]:
#khởi tạo hai mảng ngẫu nhiên bằng numpy,pytorch,tensorflow
array_np = np.random.randint(-10,10,size=(3,3))
torch_array = torch.randint(-10,10,size=(3,3))
tf_array = tf.random.uniform((3,3),-10,10,tf.int32)

In [32]:
#tính tổng toàn bộ của các ma trận
sum1 = np.sum(array_np)
sum2 = torch.sum(torch_array)
sum3 = tf.reduce_sum(tf_array)
print(sum1,"\n", sum2,"\n", sum3)

-5 
 tensor(-2) 
 tf.Tensor(-8, shape=(), dtype=int32)


In [31]:
#tính tổng theo chiều dọc
sum1v = np.sum(array_np,axis=0)
sum2v = torch.sum(torch_array,dim=0)
sum3v = tf.reduce_sum(tf_array,axis=0)
print(sum1v,"\n", sum2v, "\n",sum3v)

[ 5 -1 -9] 
 tensor([ 4,  0, -6]) 
 tf.Tensor([-15   8  -1], shape=(3,), dtype=int32)


In [33]:
#tính tổng theo chiều ngang
sum1h = np.sum(array_np,axis=1)
sum2h = torch.sum(torch_array,dim=1)
sum3h = tf.reduce_sum(tf_array,axis=1)
print(sum1h,"\n", sum2h, "\n",sum3h)

[-17   0  12] 
 tensor([-5,  3,  0]) 
 tf.Tensor([ 6 -9 -5], shape=(3,), dtype=int32)
