In [2]:
import numpy as np
import torch
import tensorflow as tf

In [8]:
# tạo mảng trong khoảng [0,10) với step = 1
array_np = np.arange(10)
print(array_np)
array_torch= torch.arange(10)
print(array_torch)
array_tf= tf.range(10)
print(array_tf)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [13]:
# tạo ma trận đơn vị với kích thước 3,3
array_np3 = np.eye(3,3)
print(array_np3,"\n")
array_torch3= torch.eye(3,3)
print(array_torch3,"\n")
array_tf= tf.eye(3,3)
print(array_tf,"\n")


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) 

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32) 



In [16]:
np.random.seed(2024)
#tạo mảng ngẫu nhiên trong khoảng [0,1)
array_radom_1 = np.random.rand(3,4)
print(array_radom_1,"\n")
#tạo mảng ngẫu nhiên trong khoảng [-10,10]
array_radom_2 = np.random.randint(-10,10,size=(3,4))
print(array_radom_2 ,"\n")

[[0.58801452 0.69910875 0.18815196 0.04380856]
 [0.20501895 0.10606287 0.72724014 0.67940052]
 [0.4738457  0.44829582 0.01910695 0.75259834]] 

[[ 5  1 -3  8]
 [-1 -4  0 -9]
 [-5  9 -6 -2]] 



In [21]:
torch.manual_seed(2024)
#tạo mảng ngẫu nhiên trong khoảng [0,1)
torch_radom_1 = torch.rand(3,4)
print(torch_radom_1,"\n")
#tạo mảng ngẫu nhiên trong khoảng [-10,10]
torch_radom_2 = torch.randint(-10,10,size=(3,4))
print(torch_radom_2,"\n")

tensor([[0.5317, 0.8313, 0.9718, 0.1193],
        [0.1669, 0.3495, 0.2150, 0.6201],
        [0.4849, 0.7492, 0.1521, 0.5625]]) 

tensor([[  1,   8,   0,  -2],
        [ -9, -10,  -9,   0],
        [ -3,  -7,  -4,   8]]) 



In [25]:
tf.random.set_seed(2024)
#tạo mảng ngẫu nhiên trong khoảng [0,1)
tf_radom_1 = tf.random.uniform((3,4),0,1)
print(tf_radom_1,"\n")
#tạo mảng ngẫu nhiên trong khoảng [-10,10]
tf_radom_2 = tf.random.uniform((3,4),-10,10,dtype= tf.dtypes.int32)
print(tf_radom_2,"\n")

tf.Tensor(
[[0.90034294 0.19453335 0.36069036 0.66361904]
 [0.76605344 0.2159369  0.6261736  0.07380784]
 [0.22062695 0.934368   0.93327904 0.69267046]], shape=(3, 4), dtype=float32) 

tf.Tensor(
[[-3 -7  9  3]
 [ 2 -5 -3 -5]
 [ 4 -3 -3  5]], shape=(3, 4), dtype=int32) 

